defaultSemverRangePrefix: ""

nodeLinker: pnp

pnpEnableEsmLoader: false

packageExtensions:
  "@jambit/eslint-plugin-typed-redux-saga@*":
    dependencies:
      typed-redux-saga: "*"
      redux-saga: "*"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
