defaultSemverRangePrefix: ""

nodeLinker: pnp

packageExtensions:
  "@jambit/eslint-plugin-typed-redux-saga@*":
    dependencies:
      redux-saga: "*"
      typed-redux-saga: "*"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-3.2.0.cjs
